# Generated by Django 4.1.6 on 2023-06-07 20:54

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    migrations.CreateModel(
        name='CustomUser',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('password', models.CharField(max_length=128, verbose_name='password')),
            ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ('username', models.CharField(blank=True, max_length=150, unique=True, verbose_name='username')),
            ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
            ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
            ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
            ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
        ],
        options={
            'abstract': False,
        },
    ),
    migrations.CreateModel(
        name='Player',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('wins', models.PositiveIntegerField(default=0)),
            ('wins_pvp', models.PositiveIntegerField(default=0)),
            ('wins_tournament', models.PositiveIntegerField(default=0)),
            ('xp', models.PositiveIntegerField(default=0)),
            ('user', models.OneToOneField(on_delete=models.CASCADE, related_name='player', to='djapi.CustomUser')),
        ],
    ),
    migrations.CreateModel(
        name='StaffCode',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('code', models.CharField(max_length=20)),
        ],
    ),
]


